### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by darlentar** [rixed/ramen#1002]
Missing qcustomplot.cpp and qcustomplot.h to compile RmAdmin.
Maybe we should remove them from .gitignore ?

**Comment by rixed** [comment]
In order not to "artificially" inflate LoC count and make it clearer that qcustomplot is in fact an external dependency, I'd rather include it as a git submodule (implying we find or create a git repo somewhere for it), or have the Makefile download it when missing.

**Comment by rixed** [comment]
Closed by c7f008e2e1834a10a
