### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by darlentar** [rixed/ramen#1003]
rmadmin.ico file is missing so we cannot compile RmAdmin. A workaround is to to type 'touch rmadmin.ico'.
Maybe we should add rmadmin.ico to gitted files (*.ico is in .gitignore file).

**Comment by rixed** [comment]
rmadmin/rmadmin.ico is build from site/icon.png which is stored in git.
Do you have imagemagick installed?

**Comment by rixed** [comment]
Fixed by ae6f3922294852ce0c7de001a48de4f3e8156c0a
