### ISSUE TITLE
empty username crash

### ISSUE THREAD

**Issue by rixed** [rixed/ramen#1123]
```
# ramen ps
Authentication: Not established: Not authenticated to the server: Invalid_argument("index out of bounds")
Cannot initialize ZMQClient
```

**Comment by darlentar** [comment]
I think I will use "anonymous" by default. WDYT ?

**Comment by rixed** [comment]
OK, but then also add a test when loading keys from users directory, to prevent anonymous to have one ;)

**Comment by darlentar** [comment]
Ok

**Comment by darlentar** [comment]
I'd remark that there are already an "_anonymous" user for Ramen internal usage. It may be confusing also if there the user is "anonymous".

**Comment by rixed** [comment]
johndoe ?
