### ISSUE TITLE
Reintroduce alert escalations

### ISSUE THREAD

**Issue by rixed** [rixed/ramen#1149]
Let's take advantage of this to finish moving the alerter away from files and into the confserver so its internal can be inspected from the GUI. Here is the plan:

1. [ ] move the alerter configuration into the confserver; configurator would then merely write this conf using for instance some new CLI tool `ramen confset --key=X --value=Y` to avoid actual connection and sync.
2. [ ] reintroduce the escalations (ie contacts become a list as in the past etc)
3. [ ] have each pending alert / ongoing incident have an entry in the confserver as well, despite the alerter keep managing them as a heap, not actually reading this part of the conftree past the initial sync, just writing it. Once finished incidents could be added a final event scheduled after some constant time for actual deletion, during which it's still available in the GUI for inspection
4. [ ] add an editor in the GUI for the alerter config

DH needs only the step 2.

**Comment by jaimeyu** [comment]
Should be tunable so we can avoid storing too many alert events to save disk space.

**Comment by rixed** [comment]
Note:
Let's get rid of the additional debouncing delay after startup (added because of this: https://github.com/rixed/ramen/issues/127) to make things simpler and faster. Also, this was not the proper fix for lack of history anyway (individual alerts should be able to set a specific min debounce delay)
