### ISSUE TITLE
add a --testmode option to confserver

### ISSUE THREAD

**Issue by darlentar** [rixed/ramen#1161]
This is to start the confserver without to specify a port so confserver will use a random one and the confserver will set RAMEN_CONFSERVER env var to this port.
This is useful fort cli tests to avoid conflicts if other ramen instances are running.

**Comment by rixed** [comment]
> the confserver will set RAMEN_CONFSERVER env var to this port

won't fly

For cli test, cli tester have to pick a random port itself.
